# Generated by Django 5.2.4 on 2025-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_trigram_ext'),
    ]

    operations = [
    ]
