# Generated by Django 5.2.9 on 2025-12-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_trigram_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
